sprint-1/step-2
blooder2006/react-burger pull request #1
Opened 2023-02-12 19:00 UTC by blooder2006

2023-02-12 20:15 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- Вынести описание повторящихся PropTypes ингредиента в отдельный файл
- Добавить `isRequired`

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Логичный и понятный код. Ничего лишнего нет.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Можно лучше**
- Рекомендую удалить файл `App.test.tsx` так как на спринте по тестам он может вызывать ошибку. Так же стоит поменять расширение у всех файлов с `tsx` на `jsx` так как `typescript` сейчас не используется.

Удачных правок!

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/app-header/app-header.js
> +        <div>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например
```
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```
В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/app/app.js
> +      .then((res) => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/app/app.js
> +        console.log("Ошибка:");
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +  selectedIngredients: PropTypes.arrayOf(
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +      _id: PropTypes.string,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +    .map((elem) => ({ ...elem, counter: 0 }));
**Можно лучше**
Для лучшей читаемости добавляйте пустую строку между длинными многострочными инициализациями

2023-02-12 20:15 UTC, andryxxa93 commented on src/components/modal/modal.js
> +      document.removeEventListener("keydown", checkEscape);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-02-12 20:15 UTC, andryxxa93 commented on tsconfig.json
> +{
**Можно лучше**
`tsconfig.json` можно удалить - сейчас этот конфиг не нужен, так как `typescript` не используется. В будущем будет спринт посвященный этой технологии.

2023-02-12 22:12 UTC, blooder2006 commented on src/components/app-header/app-header.js
> +        <div>
исправлено

2023-02-12 22:12 UTC, blooder2006 commented on src/components/app/app.js
> +      .then((res) => res.json())
исправлено

2023-02-12 22:12 UTC, blooder2006 commented on src/components/burger-constructor/burger-constructor.js
> +  selectedIngredients: PropTypes.arrayOf(
исправлено

2023-02-12 22:12 UTC, blooder2006 commented on src/components/burger-constructor/burger-constructor.js
> +      _id: PropTypes.string,
исправлено

2023-02-12 22:12 UTC, blooder2006 commented on tsconfig.json
> +{
учтено

2023-02-12 22:12 UTC, blooder2006 commented on src/components/modal/modal.js
> +      document.removeEventListener("keydown", checkEscape);
спасибо!

2023-02-12 22:13 UTC, blooder2006 commented on src/components/burger-ingredients/burger-ingredients.js
> +    .map((elem) => ({ ...elem, counter: 0 }));
учтено

2023-02-12 22:13 UTC, blooder2006 commented on src/components/app/app.js
> +        console.log("Ошибка:");
учтено

2023-02-13 07:38 UTC, andryxxa93 requested changes
Всё отлично! Вы очень хорошо поработали. 
Есть только одно замечание - 
В консоли есть ошибка связанная `propTypes` - обратите внимание на то какие пропсы вы указали в `propTypes` у `Modal` и какие приходят на самом деле.
<img width="1440" alt="Снимок экрана 2023-02-13 в 10 35 16" src="https://user-images.githubusercontent.com/60173362/218397969-66db5a95-50bd-41d5-812f-b7bfe9055b93.png">

2023-02-13 08:50 UTC, blooder2006 commented
> Всё отлично! Вы очень хорошо поработали. Есть только одно замечание - В консоли есть ошибка связанная `propTypes` - обратите внимание на то какие пропсы вы указали в `propTypes` у `Modal` и какие приходят на самом деле. 
Исправил. У header не стал ставить isRequired, поскольку заголовка у модального окна может и не быть.
Поправил в стилях ширину заголовка - иначе перекрывал кнопку закрытия

2023-02-13 10:42 UTC, andryxxa93 approved these changes
Супер! Все замечания исправлены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-02-13 18:48 UTC, merged