sprint-2/step-1
blooder2006/react-burger pull request #2
Opened 2023-02-17 11:09 UTC by blooder2006

For sprint-2/step-1

2023-02-17 11:50 UTC, andryxxa93 requested changes
Здравствуйте! У вас очень хороший проект.
Что понравилось:
- Очень хорошая типизация `propTypes`
- В проекте отсутствует лишний код
- Используется `useReducer` для подсчета стоимости и добавления ингредиентов
- В контекст обернуты только те компоненты, которые будут его использовать

Что необходимо исправить:
- Теперь массив ингредиентов необходимо передавать через контекст, а не через пропсы как сейчас реализовано с `BurgerIngredients`.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-17 11:50 UTC, andryxxa93 commented on src/utils/order-context.js
> +export const orderContext = React.createContext([]);
**Можно лучше**
Название компонента стоит писать с заглавной буквы - элемент в который мы оборачиваем компоненты для передачи контекста так же является компонентом.

2023-02-17 11:50 UTC, andryxxa93 commented on src/components/app/app.js
> +      dispatch({ type: "changeTotalPrice", payload: totalPrice });
**Можно лучше**
Хоть в задании и рекомендуется использовать для подсчета `useReducer` на самом деле это можно сделать более простым способом. 
Примерно вот таким:
```
const price = useMemo(() => {
    return (
      (constructorItems.bun ? constructorItems.bun.price * 2 : 0) +
      constructorItems.ingredients.reduce((s, v) => s + v.price, 0)
    );
  }, [constructorItems]);
```

Но это здорово, что вы попробовали хук `useReducer` - понимание его работы поможет вам в освоении стейт менеджера `redux`.

2023-02-18 11:39 UTC, blooder2006 commented on src/utils/order-context.js
> +export const orderContext = React.createContext([]);
Исправил

2023-02-18 11:40 UTC, blooder2006 commented on src/components/app/app.js
> +      dispatch({ type: "changeTotalPrice", payload: totalPrice });
Пока оставил использование useReducer, чтобы соответствовало заданию

2023-02-18 21:10 UTC, andryxxa93 requested changes
Компонент `BurgerIngredients` по-прежнему получает ингредиенты через пропсы, а не через контекст. Исправьте это и ваша работа будет принята.

2023-02-18 21:23 UTC, blooder2006 commented
> Компонент `BurgerIngredients` по-прежнему получает ингредиенты через пропсы, а не через контекст. Исправьте это и ваша работа будет принята.

Извиняюсь, в предыдущий раз неправильно запушил правки

2023-02-19 07:13 UTC, andryxxa93 approved these changes
Супер, теперь всё отлично! Ваша работа принята, удачного продолжения обучения!

2023-02-19 16:44 UTC, merged